// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBroFtnt6Un5osQfppjU4VIwXjbgNUbkpw',
    appId: '1:418404573707:web:7632eb5448a2c2bd691d0e',
    messagingSenderId: '418404573707',
    projectId: 'kitchenmaster-ae07b',
    authDomain: 'kitchenmaster-ae07b.firebaseapp.com',
    storageBucket: 'kitchenmaster-ae07b.appspot.com',
    measurementId: 'G-JV4J2L58H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhugXImRS6NybdDwqAjeWuIan8ZHYI54U',
    appId: '1:418404573707:android:5e68d8ddb4a07fe6691d0e',
    messagingSenderId: '418404573707',
    projectId: 'kitchenmaster-ae07b',
    storageBucket: 'kitchenmaster-ae07b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPGYzO0MIG6a2jGPd4sPzRDOVfyJPhJKw',
    appId: '1:418404573707:ios:08eebddefccd62b0691d0e',
    messagingSenderId: '418404573707',
    projectId: 'kitchenmaster-ae07b',
    storageBucket: 'kitchenmaster-ae07b.appspot.com',
    iosClientId: '418404573707-5k03foiahskopcg8rvt51jp8jerfo7uk.apps.googleusercontent.com',
    iosBundleId: 'com.example.fridgemaster',
  );
}
